apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 4
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: 843756393997.dkr.ecr.ap-south-1.amazonaws.com/2nd10weeksofcloudops-main-backend:latest
        ports:
        - containerPort: 80
        env:
        - name: DB_HOST
          value: "mysql"
        - name: DB_USERNAME
          value: "admin"
        - name: DB_PASSWORD
          value: "Devops123"
        - name: DB_PORT
          value: "3306"
        - name: DB_NAME
          value: "test"
        - name: PORT
          value: "3306"  # Change if your backend listens on a different port
