apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: 843756393997.dkr.ecr.ap-south-1.amazonaws.com/2nd10weeksofcloudops-main-mysql:latest
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "Cloud123"
            - name: MYSQL_DATABASE
              value: "test"
            - name: MYSQL_USER
              value: "admin"
            - name: MYSQL_PASSWORD
              value: "Devops123"
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          emptyDir: {}  # Replace with PersistentVolumeClaim in production
